version: '3'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'usersdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'